include(FindPackageHandleStandardArgs)
find_package(PkgConfig)
if(PKGCONFIG_FOUND)
    pkg_check_modules(ASSIMP assimp)
    if(ASSIMP_VERSION)
        if(ASSIMP_VERSION STRGREATER "2.0.0")
            set(OMPL_HAS_ASSIMP3 1)
        else()
            set(OMPL_HAS_ASSIMP2 1)
        endif()
    endif()
endif()

find_package_handle_standard_args(assimp DEFAULT_MSG ASSIMP_LIBRARIES ASSIMP_INCLUDE_DIRS)
