include(FindPackageHandleStandardArgs)
find_package(PkgConfig)
if(PKGCONFIG_FOUND)
    pkg_check_modules(FCL fcl>=0.3.1)
endif()
find_package_handle_standard_args(FCL DEFAULT_MSG FCL_LIBRARIES FCL_INCLUDE_DIRS)
