# AppVeyor file
# http://www.appveyor.com/docs/appveyor-yml

version: "{build}"
os: Visual Studio 2017

clone_folder: C:\projects\omplapp
shallow_clone: true

platform: x64

environment:
  CTEST_OUTPUT_ON_FAILURE: 1
  CMAKE_TOOLCHAIN_FILE: -DCMAKE_TOOLCHAIN_FILE="C:\tools\vcpkg\scripts\buildsystems\vcpkg.cmake"
  CMAKE_GENERATOR: -G"Visual Studio 15 2017 Win64"
  VCPKG_ARCH: x64-windows

cache:
  - C:\tools\vcpkg\installed -> .appveyor.yml

configuration: Release

before_build:
  - cmd: git -C c:\tools\vcpkg\ fetch
  - cmd: git -C c:\tools\vcpkg\ checkout 2025.04.09
  - cmd: c:\tools\vcpkg\bootstrap-vcpkg.bat
  - cmd: vcpkg x-set-installed --triplet %VCPKG_ARCH%
         assimp
         boost-dynamic-bitset
         boost-filesystem
         boost-graph
         boost-odeint
         boost-program-options
         boost-serialization
         boost-system
         boost-test
         boost-ublas
         eigen3
         fcl
  - cmd: git clone -q --depth=1 --branch=main https://github.com/ompl/ompl.git C:\projects\omplapp\ompl
  - cmd: mkdir build
  - cmd: cd build
  - cmd: cmake %CMAKE_GENERATOR% -DCMAKE_BUILD_TYPE=%configuration% %CMAKE_TOOLCHAIN_FILE% -DOMPL_REGISTRATION=OFF ..

build:
  project: C:\projects\omplapp\build\omplapp.sln
  parallel: true

after_build:
  - cmd: cmake --build . --config %configuration% --target package

test_script:
  - cmd: ctest -C %configuration%

artifacts:
  - path: 'build\omplapp*.zip'
