.TH OMPL_BENCHMARK 1
.SH NAME
ompl_webapp \- start the OMPL web app
.SH SYNOPSIS
.B ompl_webapp
.SH DESCRIPTION
.BR ompl_webapp
is a script that launches the OMPL web app server locally. It should look
similar to http://omplapp.kavrakilab.org. By default, the server can be
accessed by visiting http://127.0.0.1:5000 in your browser.
.SH SEE ALSO
.B ompl_conf(5), plannerarena(1), ompl_app(1)
